// Code generated by bleve/search/scorer/simd/gen (via avo). DO NOT EDIT.

//go:build amd64 && !purego

package simd

const hasAsm = true

//go:noescape
func bm25Asm(freqs *uint64, norms *float64, idf, k1, oneMinusB, b, invAvgDocLength, queryWeight float64, out *float64, numPairs int)

//go:noescape
func tfidfAsm(freqs *uint64, norms *float64, idf, queryWeight float64, out *float64, numPairs int)

func bm25(freqs []uint64, norms []float64, idf, k1, oneMinusB, b, invAvgDocLength, queryWeight float64, out []float64, n int) {
	if n == 0 {
		return
	}
	bm25Asm(&freqs[0], &norms[0], idf, k1, oneMinusB, b, invAvgDocLength, queryWeight, &out[0], n/2)
}

func tfidf(freqs []uint64, norms []float64, idf, queryWeight float64, out []float64, n int) {
	if n == 0 {
		return
	}
	tfidfAsm(&freqs[0], &norms[0], idf, queryWeight, &out[0], n/2)
}
