// Code generated by command: go run asm.go -out kernels_amd64.s -stubs /dev/null -pkg simd. DO NOT EDIT.

#include "textflag.h"

// func bm25Asm(freqs *uint64, norms *float64, idf float64, k1 float64, oneMinusB float64, b float64, invAvgDocLength float64, queryWeight float64, out *float64, numPairs int)
// Requires: SSE2
TEXT ·bm25Asm(SB), NOSPLIT, $0-80
	MOVQ     freqs+0(FP), AX
	MOVQ     norms+8(FP), CX
	MOVQ     out+64(FP), DX
	MOVQ     numPairs+72(FP), BX
	MOVSD    idf+16(FP), X0
	UNPCKLPD X0, X0
	MOVSD    k1+24(FP), X1
	UNPCKLPD X1, X1
	MOVSD    oneMinusB+32(FP), X2
	UNPCKLPD X2, X2
	MOVSD    b+40(FP), X3
	UNPCKLPD X3, X3
	MOVSD    invAvgDocLength+48(FP), X4
	UNPCKLPD X4, X4
	MOVSD    queryWeight+56(FP), X5
	UNPCKLPD X5, X5
	MOVQ     $0x3ff0000000000000, SI
	MOVQ     SI, X6
	UNPCKLPD X6, X6
	MOVQ     $0x0000000000000000, SI

loop:
	CMPQ     SI, BX
	JGE      done
	MOVQ     (AX), DI
	MOVQ     8(AX), R8
	CVTSQ2SD DI, X7
	CVTSQ2SD R8, X8
	UNPCKLPD X8, X7
	SQRTPD   X7, X7
	MOVUPD   (CX), X9
	MOVUPD   X9, X10
	MULPD    X9, X10
	MOVUPD   X6, X9
	DIVPD    X10, X9
	MOVUPD   X3, X10
	MULPD    X9, X10
	MOVUPD   X10, X9
	MULPD    X4, X9
	MOVUPD   X2, X10
	ADDPD    X9, X10
	MOVUPD   X1, X9
	MULPD    X10, X9
	MOVUPD   X7, X10
	ADDPD    X9, X10
	MOVUPD   X7, X9
	MULPD    X1, X9
	MOVUPD   X0, X11
	MULPD    X9, X11
	MOVUPD   X11, X9
	DIVPD    X10, X9
	MOVUPD   X9, X9
	MULPD    X5, X9
	MOVUPD   X9, (DX)
	ADDQ     $0x10, AX
	ADDQ     $0x10, CX
	ADDQ     $0x10, DX
	INCQ     SI
	JMP      loop

done:
	RET

// func tfidfAsm(freqs *uint64, norms *float64, idf float64, queryWeight float64, out *float64, numPairs int)
// Requires: SSE2
TEXT ·tfidfAsm(SB), NOSPLIT, $0-48
	MOVQ     freqs+0(FP), AX
	MOVQ     norms+8(FP), CX
	MOVQ     out+32(FP), DX
	MOVQ     numPairs+40(FP), BX
	MOVSD    idf+16(FP), X0
	UNPCKLPD X0, X0
	MOVSD    queryWeight+24(FP), X1
	UNPCKLPD X1, X1
	MOVQ     $0x0000000000000000, SI

loop:
	CMPQ     SI, BX
	JGE      done
	MOVQ     (AX), DI
	MOVQ     8(AX), R8
	CVTSQ2SD DI, X2
	CVTSQ2SD R8, X3
	UNPCKLPD X3, X2
	SQRTPD   X2, X2
	MOVUPD   (CX), X4
	MOVUPD   X2, X5
	MULPD    X4, X5
	MULPD    X0, X5
	MOVUPD   X5, X4
	MULPD    X1, X4
	MOVUPD   X4, (DX)
	ADDQ     $0x10, AX
	ADDQ     $0x10, CX
	ADDQ     $0x10, DX
	INCQ     SI
	JMP      loop

done:
	RET
