//go:build arm64 && !purego
// Code generated by bleve/search/scorer/simd/gen (via goat). DO NOT EDIT.
// versions:
// 	clang   21.0.0 (clang-2100.1.1.101)
// 	objdump 2.47.20260726
// flags: -O3
// source: kernels_arm64.c
#include "textflag.h"

TEXT ·bm25Asm(SB), NOSPLIT|NOFRAME, $0-80
	MOVD  freqs+0(FP), R0
	MOVD  norms+8(FP), R1
	FMOVD idf+16(FP), F0
	FMOVD k1+24(FP), F1
	FMOVD oneMinusB+32(FP), F2
	FMOVD b+40(FP), F3
	FMOVD invAvgDocLength+48(FP), F4
	FMOVD queryWeight+56(FP), F5
	MOVD  out+64(FP), R2
	MOVD  numPairs+72(FP), R3
	WORD  $0xf100047f                // cmp	x3, #1
	BLT   LBB0_3
	WORD  $0x6f03f606                // fmov	v6.2d, #1.00000000
	WORD  $0x4e080442                // dup	v2.2d, v2.d[0]

LBB0_2:
	WORD $0x3cc10427 // ldr	q7, [x1], #16
	WORD $0x4ea21c51 // mov	v17.16b, v2.16b
	WORD $0x3cc10410 // ldr	q16, [x0], #16
	WORD $0xf1000463 // subs	x3, x3, #1
	WORD $0x6e67dce7 // fmul	v7.2d, v7.2d, v7.2d
	WORD $0x6e61da10 // ucvtf	v16.2d, v16.2d
	WORD $0x6e67fcc7 // fdiv	v7.2d, v6.2d, v7.2d
	WORD $0x6ee1fa10 // fsqrt	v16.2d, v16.2d
	WORD $0x4fc390e7 // fmul	v7.2d, v7.2d, v3.d[0]
	WORD $0x4fc410f1 // fmla	v17.2d, v7.2d, v4.d[0]
	WORD $0x4fc19207 // fmul	v7.2d, v16.2d, v1.d[0]
	WORD $0x4fc11230 // fmla	v16.2d, v17.2d, v1.d[0]
	WORD $0x4fc090e7 // fmul	v7.2d, v7.2d, v0.d[0]
	WORD $0x6e70fce7 // fdiv	v7.2d, v7.2d, v16.2d
	WORD $0x4fc590e7 // fmul	v7.2d, v7.2d, v5.d[0]
	WORD $0x3c810447 // str	q7, [x2], #16
	BNE  LBB0_2

LBB0_3:
	RET

TEXT ·tfidfAsm(SB), NOSPLIT|NOFRAME, $0-48
	MOVD  freqs+0(FP), R0
	MOVD  norms+8(FP), R1
	FMOVD idf+16(FP), F0
	FMOVD queryWeight+24(FP), F1
	MOVD  out+32(FP), R2
	MOVD  numPairs+40(FP), R3
	WORD  $0xf100047f            // cmp	x3, #1
	BLT   LBB1_2

LBB1_1:
	WORD $0x3cc10402 // ldr	q2, [x0], #16
	WORD $0xf1000463 // subs	x3, x3, #1
	WORD $0x3cc10423 // ldr	q3, [x1], #16
	WORD $0x6e61d842 // ucvtf	v2.2d, v2.2d
	WORD $0x6ee1f842 // fsqrt	v2.2d, v2.2d
	WORD $0x6e62dc62 // fmul	v2.2d, v3.2d, v2.2d
	WORD $0x4fc09042 // fmul	v2.2d, v2.2d, v0.d[0]
	WORD $0x4fc19042 // fmul	v2.2d, v2.2d, v1.d[0]
	WORD $0x3c810442 // str	q2, [x2], #16
	BNE  LBB1_1

LBB1_2:
	RET
